// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mob.Models;

namespace Mob.Migrations
{
    [DbContext(typeof(MobContext))]
    partial class MobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Mob.Models.Criminal", b =>
                {
                    b.Property<int>("CriminalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CriminalId");

                    b.ToTable("Criminals");
                });

            modelBuilder.Entity("Mob.Models.CriminalJob", b =>
                {
                    b.Property<int>("CriminalJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CriminalId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.HasKey("CriminalJobId");

                    b.HasIndex("CriminalId");

                    b.HasIndex("JobId");

                    b.ToTable("CriminalJob");
                });

            modelBuilder.Entity("Mob.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Mob.Models.CriminalJob", b =>
                {
                    b.HasOne("Mob.Models.Criminal", "Criminal")
                        .WithMany("Jobs")
                        .HasForeignKey("CriminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mob.Models.Job", "Job")
                        .WithMany("Criminals")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criminal");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Mob.Models.Criminal", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Mob.Models.Job", b =>
                {
                    b.Navigation("Criminals");
                });
#pragma warning restore 612, 618
        }
    }
}
